### ISSUE TITLE
Packdown Workflow Failing

### ISSUE THREAD

**Issue by gowerc** [insightsengineering/r.pkg.template#50]
The packagedown workflow is erroring when I attempt to use it.  Apologies if this is a simple config issue but there isn't much in the way of documentation on how to configure it :( 

Failed build: https://github.com/insightsengineering/rbmi/runs/5083567889?check_suite_focus=true

Workflow Implementation: https://github.com/insightsengineering/rbmi/blob/main/.github/workflows/packagedown.yaml

**Comment by dinakar29** [comment]
https://github.com/insightsengineering/rbmi/pull/289 should address the issue.

**Comment by dinakar29** [comment]
Associated docs: https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview

**Comment by dinakar29** [comment]
That didn't work. Looking into other options.

**Comment by dinakar29** [comment]
@gowerc - publishing will not work unless you allow Github Actions to be able to write to your repo:
![image](https://user-images.githubusercontent.com/26552821/154314161-be2cef5d-06ba-45cd-8f6d-a335dbab0a8e.png)

Do you want to enable that?

**Comment by gowerc** [comment]
yes please, does this require a change to the config repo ?

**Comment by dinakar29** [comment]
No this can be manually configured.

**Comment by dinakar29** [comment]
> No this can be manually configured.

I have enabled it for your repo.

**Comment by gowerc** [comment]
O ha was about to say it was already enabled and that I don't understand, you beat me to it :) ty !

**Comment by dinakar29** [comment]
Docs published here: https://insightsengineering.github.io/rbmi/
