### ISSUE TITLE
styler - github source - newest

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/r.pkg.template#51]
`styler` package is not updated for a long time, half a year.
In last time @Polkas and @kpagacz find two important problems with were ALREADY solved on styler main branch.
Problems:
- substitute(aa %>% bb, env = list(aa = quote(fun()), )) -> styler was wrongly adding brackets () to aa()
- turn off styler functionality was broken

**Comment by pawelru** [comment]
isn't it already closed with https://github.com/insightsengineering/r.pkg.template/pull/52 ?
