### ISSUE TITLE
Rename `_pkgdown.yaml` into `_pkgdown.yml`

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/r.pkg.template#55]
Please rename the pkgdown file as the `.yaml` extension gives a note in R CMD CHECK:

```
N  checking top-level files
   Non-standard file/directory found at top level:
     ‘_pkgdown.yaml’
```

**Comment by dinakar29** [comment]
Updated the filename in https://github.com/insightsengineering/r.pkg.template/pull/54. Thanks for the report.

**Comment by dinakar29** [comment]
This is done.
